name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. 앱 디렉토리가 없으면 GitHub에서 clone
            if [ ! -d "/home/ubuntu/my-node-app" ]; then
              git clone https://github.com/minseo0059/my-node-app.git /home/ubuntu/my-node-app
            fi

            # 2. 앱 디렉토리로 이동
            cd /home/ubuntu/my-node-app

            # 3. 최신 코드로 업데이트 (main 브랜치 기준)
            git pull origin main

            # 4. Node.js 의존성 설치
            npm install

            # 5. pm2로 앱 실행 또는 재시작
            if pm2 list | grep -q "app"; then
              pm2 restart app
            else
              pm2 start app.js --name app
            fi
